### ISSUE TITLE
SDDM doesn't start on live session

### ISSUE THREAD

**Issue by joostruis** [mocaccinoOS/desktop#127] opened 2021-06-22 09:26 UTC
On de KDE -dev iso SDDM won't start on the live session. After install it works fine.

**Comment by msdobrescu** [comment] 2021-07-02 14:20
Could this be related to a display driver problem?

**Comment by msdobrescu** [comment] 2021-07-02 16:29
My workaround is this, as the content of /lib/systemd/system/sddm.service:

`[Unit]
Description=Simple Desktop Display Manager
Documentation=man:sddm(1) man:sddm.conf(5)
After=systemd-user-sessions.service getty@tty1.service systemd-logind.service

[Service]
ExecStart=/usr/bin/sddm
Restart=always
BusName=org.freedesktop.DisplayManager

[Install]
Alias=display-manager.service`

I think the Conflict entry for the tty was the cause, I am not yet sure.

![VirtualBox_Mocaccino_02_07_2021_19_27_54](https://user-images.githubusercontent.com/7279637/124303890-a750b500-db6b-11eb-9889-27350fbf1fd0.png)

**Comment by joostruis** [comment] 2021-07-02 18:19
> Could this be related to a display driver problem?

no.

**Comment by msdobrescu** [comment] 2021-07-02 19:07
> > Could this be related to a display driver problem?
> 
> no.

Indeed.

**Comment by msdobrescu** [comment] 2021-07-02 20:32
Shouldn't there be /etc/sddm.conf file?

**Comment by msdobrescu** [comment] 2021-07-02 20:41
According to my tests, the service should be:

`[Unit]
Description=Simple Desktop Display Manager
Documentation=man:sddm(1) man:sddm.conf(5)
After=systemd-user-sessions.service getty@tty1.service plymouth-quit.service systemd-logind.service

[Service]
ExecStart=/usr/bin/sddm
Restart=always
BusName=org.freedesktop.DisplayManager

[Install]
Alias=display-manager.service`

Do you confirm?

**Comment by msdobrescu** [comment] 2021-07-03 05:04
A strange behavior occurs with this setup. After the KDE Plasma start, the "Welcome to MocaccinoOS" page appears in Chrome.
This seems to start before Plasma desktop, as the start bemu, start bar etc. appear after it.
If the user does not close this Chrome instance and tries to shutdown, Chrome instance persists, it remains as a window, but lacking a caption and a possibility to stop it, over a black desktop:

![VirtualBox_Mocaccino_03_07_2021_07_56_28](https://user-images.githubusercontent.com/7279637/124343545-ea933e00-dbd4-11eb-932d-74f05bbde860.png)

If the user logs out, login screen appears again, the first Chrome instance is closed and the user can initiate a new KDE Plasma seession as root again. At this point, the user can shutdown successfully, as the new Chrome instance is closed.

**Comment by joostruis** [comment] 2021-07-03 17:12
@msdobrescu 
Hmm you might be right about the change in the service file.
We already do a simular thingy for gdm:
https://github.com/mocaccinoOS/desktop/blob/master/packages/mocaccino/live-setup/live-functions.sh#L36

**Closed** 2021-07-03 18:44 UTC
